        <div class="tab-pane fade show active" id="login" role="tabpanel">
            <form method="post">
            <div class="form-floating mb-3">
                <input type="text" class="form-control" id="loginEmail" name="login" placeholder="email@exemplo.com" required />
                <label for="loginEmail">E-mail</label>
            </div>
            <div class="form-floating mb-3">
                <input type="password" class="form-control" id="loginSenha" name="senha" placeholder="Senha" required />
                <label for="loginSenha">Senha</label>
            </div>
            <div class="d-grid mb-3">
                <button type="submit" class="btn btn-success btn-lg">Entrar</button>
            </div>
            <div class="text-center text-muted">
                <small><a href="#">Esqueceu a senha?</a></small>
            </div>
            </form>
        </div>