      <div class="tab-pane fade" id="register" role="tabpanel">
        <form method="post">
          <div class="form-floating mb-3">
            <input type="text" class="form-control" id="regNome" placeholder="Seu nome completo" required />
            <label for="regNome">Nome completo</label>
          </div>
          <div class="form-floating mb-3">
            <input type="email" class="form-control" id="regEmail" placeholder="email@exemplo.com" required />
            <label for="regEmail">E-mail</label>
          </div>
          <div class="form-floating mb-3">
            <input type="password" class="form-control" id="regSenha" name="senha" placeholder="Senha" required />
            <label for="regSenha">Senha</label>
          </div>
          <div class="d-grid mb-3">
            <button type="submit" class="btn btn-success btn-lg">Cadastrar</button>
          </div>
        </form>
      </div>