<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastrar</title>
</head>
<body>
	<form method="POST">
		Nome:<input type="text" name="nm_usuario"/><br><br>
		Senha:<input type="text" name="senha_usuario"/><br><br>
		Confirmar Senha: <input type="password" name="senha_confi"/><br><br>
		<button type="submit">Cadastrar</button><br><br>
	</form>
	<a href="?controle=usuario&metodo=logarUsuario">Voltar</a>
</body>
</html>