<?php
//session_start();
var_dump(session_status());

if(!Validador::isLogado())
    echo "Não tem ninguem logado";
/*$yuuna = "ds";
$teste = "ds";
$senha = password_hash("ds",PASSWORD_BCRYPT);
echo $senha;
var_dump(password_verify($teste,$senha));*/
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <form method="POST">
        Nome: <input type="text" name="login"/><br><br>
        Senha: <input type="password" name="senha"/><br><br>
        <button type="submit">Entrar</button>
    </form>
    <br><br>
    <a href="?controle=usuario&metodo=cadastrarUsuario">Cadastre-se</a>
</body>
</html>